version: '3'
services: 
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /volume1/docker/heimdall:/config
    ports:
      - 8085:80
    restart: unless-stopped

networks:
  default:
    driver: bridge