version: 3
services:
  portainer-ce:
    image: portainer/portainer-ce:2.14.2
    ports:
        - 9444:9443 # https
    container_name: portainer
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock #the first part referes to boot2docker in the VM
        - /volumes1/docker/portainer:/data #indica la tuya