version: '3'
services:
  netdata:
    container_name: serverStats-netdata
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
  file-browser:
    image: filebrowser/filebrowser
    container_name: fileSystem-filebrowser
    ports:
      - 20001:80
    volumes:
      - D:\Documents:/srv
      - D:\Server-config\FileBrowser\filebrowser.db:/database.db
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: torrentIndexer-prowlarr
    restart: unless-stopped
    ports:
    - 9696:9696
    volumes:
    - D:\Server-config\prowlarr:/config
    environment:
      TZ: Europe/Dublin
  radarr:
    image: linuxserver/radarr
    container_name: Movies-radarr
    ports:
      - 7878:7878 # port mapping
    volumes:
      - D:\Server-config\radarr:/config # config directory for radarr
      - D:\temp\downloads\complete:/downloads/complete # completed downloads directory from sab
      - D:\temp\downloads:/downloads
      - D:\Documents\Movies:/storage/Movies # where radarr will copy your movies. add as many of these as you need
    environment:
      TZ: Europe/Dublin
  sonarr:
    image: linuxserver/sonarr
    container_name: TvShows-sonarr
    ports:
      - 8989:8989
    volumes:
      - D:\Server-config\sonarr:/config # sonarr config dir
      - D:\temp\downloads\complete:/downloads/complete # your completed downloads directory from sab
      - D:\temp\downloads:/downloads
      - D:\Documents\Shows:/storage/TV # where it will copy your files when done. 
    environment:
      TZ: Europe/Dublin

  #note: readarr still on pre-alpha, this version is from 2021-12-17 10:15:38
  readarr:
    image: hotio/readarr:nightly-ef5a837
    container_name: books-readarr
    environment:
      TZ: Europe/Dublin
    volumes:
      - D:\Server-config\readarr:/config
      - D:\Documents\Books:/books
      - D:\temp\downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
  # torrent client
  transmission:
    image: linuxserver/transmission
    container_name: torrentClient-transmission
    environment:
      TZ: Europe/Dublin
    ports:
    #webUI
      - "9091:9091/tcp"
    #DataPorts
      - "51413:51413/tcp"
      - "51413:51413/udp"
    volumes:
      - D:\Server-config\transmission:/config
      - D:\temp\downloads:/downloads
      - D:\temp\downloads\complete:/downloads/complete
      - D:\temp\downloads\incomplete:/downloads/incomplete
    restart: unless-stopped
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
      UMASK_SET: 022
      VERSION: docker
    ports:
      - "32400:32400" # (for access to the Plex Media Server) [required]
      - "3005:3005" # (for controlling Plex Home Theater via Plex Companion)
      - "8324:8324" # (for controlling Plex for Roku via Plex Companion)
      - "32410:32410/udp" # (for current GDM network discovery)
      - "32412:32412/udp" # (for current GDM network discovery)
      - "32413:32413/udp" # (for current GDM network discovery)
      - "32414:32414/udp" # (for current GDM network discovery)
      - "32469:32469" # (for access to the Plex DLNA Server)
    volumes:
      - D:\Server-config\plex\config:/config
      - D:\Server-config\plex\transcode:/transcode # optional
      - D:\Documents\Movies:/data/Movies:ro
      - D:\Documents\Shows:/data/Television:ro
  nginx:
    image: nginx
    container_name: reverseProxy-nginx
    ports:
      - 80:80
    volumes:
      - D:\Server-config\nginx\default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      NGINX_HOST: server.home
    depends_on:
      - plex
      - transmission
      - sonarr
      - radarr
      - prowlarr
      - file-browser
      - netdata
      - readarr
    # Working on
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre-books
    environment:
      TZ: Europe/Dublin
    volumes:
    - D:\Server-config\calibre\config:/config
    - D:\Documents\Books:/books
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
  calibreweb:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibreweb-books
    environment:
      TZ: Europe/Dublin
    volumes:
    - D:\Server-config\calibre\config:/config
    - D:\Documents\Books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
